from __future__ import annotations
import typing
__all__: list[str] = ['MdApi']
class MdApi:
    def __init__(self) -> None:
        ...
    def createTapQuoteAPI(self, arg0: dict) -> int:
        ...
    def disconnect(self) -> int:
        ...
    def getTapQuoteAPIVersion(self) -> str:
        ...
    def init(self) -> None:
        ...
    def login(self, arg0: dict) -> int:
        ...
    def onAPIReady(self) -> None:
        ...
    def onDisconnect(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def onRspLogin(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: dict) -> None:
        ...
    def onRspQryCommodity(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryContract(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspSubscribeQuote(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspUnSubscribeQuote(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRtnQuote(self, arg0: dict) -> None:
        ...
    def qryCommodity(self) -> int:
        ...
    def qryContract(self, arg0: dict) -> int:
        ...
    def setAPINotify(self) -> int:
        ...
    def setHostAddress(self, arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def setTapQuoteAPIDataPath(self, arg0: str) -> int:
        ...
    def setTapQuoteAPILogLevel(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def subscribeQuote(self, arg0: dict) -> int:
        ...
    def unSubscribeQuote(self, arg0: dict) -> int:
        ...
