from __future__ import annotations
import typing
__all__: list[str] = ['TdApi']
class TdApi:
    def __init__(self) -> None:
        ...
    def activateOrder(self, arg0: dict) -> int:
        ...
    def addUserTrustDevice(self, arg0: dict) -> int:
        ...
    def amendOrder(self, arg0: dict) -> int:
        ...
    def authPassword(self, arg0: dict) -> int:
        ...
    def cancelHKMarketOrder(self, arg0: dict) -> int:
        ...
    def cancelOrder(self, arg0: dict) -> int:
        ...
    def changePassword(self, arg0: dict) -> int:
        ...
    def createITapTradeAPI(self, arg0: dict) -> int:
        ...
    def delUserTrustDevice(self, arg0: dict) -> int:
        ...
    def disconnect(self) -> int:
        ...
    def fillLocalInput(self, arg0: dict) -> int:
        ...
    def fillLocalRemove(self, arg0: dict) -> int:
        ...
    def getITapErrorDescribe(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> str:
        ...
    def getITapTradeAPIVersion(self) -> str:
        ...
    def haveCertainRight(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    def init(self) -> None:
        ...
    def insertHKMarketOrder(self, arg0: str, arg1: str, arg2: dict) -> int:
        ...
    def insertOrder(self, arg0: str, arg1: dict) -> int:
        ...
    def insertSpecialOrder(self, arg0: str, arg1: dict) -> int:
        ...
    def login(self, arg0: dict) -> int:
        ...
    def onAPIReady(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def onConnect(self, arg0: str) -> None:
        ...
    def onDisconnect(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def onExpriationDate(self, arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def onHKMarketQuoteNotice(self, arg0: dict) -> None:
        ...
    def onRspAddAccountIPO(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspAddUserTrustDevice(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspAuthPassword(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def onRspCancelAccountIPO(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspChangePassword(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def onRspDelUserTrustDevice(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspFillLocalInput(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspFillLocalRemove(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspHKMarketOrderDelete(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspHKMarketOrderInsert(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspLogin(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: dict) -> None:
        ...
    def onRspOrderAction(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspOrderLocalInput(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspOrderLocalModify(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspOrderLocalRemove(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspOrderLocalTransfer(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspQryAccount(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryAccountCashAdjust(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryAccountFeeRent(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryAccountIPO(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryAccountMarginRent(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryBill(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryCombinePosition(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryCommodity(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryContract(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryCurrency(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryExchange(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryExchangeStateInfo(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryFill(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryFund(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryHisDelivery(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryHisFund(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryHisMatch(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryHisOrder(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryHisOrderProcess(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryHisPosition(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryIPOInfo(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryIPOStockQty(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryOrder(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryOrderProcess(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryPosition(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryPositionSummary(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQrySpecialOrder(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQrySpotLock(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryTradeMessage(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspQryTradingDate(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspQryUserTrustDevice(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspRequestVertificateCode(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspResetPassword(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def onRspSelfPasswordInfoOperate(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def onRspSetReservedInfo(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str) -> None:
        ...
    def onRspSetVertificateCode(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def onRspSpecialOrderAction(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: dict) -> None:
        ...
    def onRspSubmitUserLoginInfo(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: str, arg3: dict) -> None:
        ...
    def onRspVerificateIdentityInfo(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def onRtnAddAccountIPO(self, arg0: dict) -> None:
        ...
    def onRtnAddUserTrustDevice(self, arg0: dict) -> None:
        ...
    def onRtnCancelAccountIPO(self, arg0: dict) -> None:
        ...
    def onRtnCombinePosition(self, arg0: dict) -> None:
        ...
    def onRtnContactInfo(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: str, arg2: str) -> None:
        ...
    def onRtnContract(self, arg0: dict) -> None:
        ...
    def onRtnDelUserTrustDevice(self, arg0: dict) -> None:
        ...
    def onRtnExchangeStateInfo(self, arg0: dict) -> None:
        ...
    def onRtnFill(self, arg0: dict) -> None:
        ...
    def onRtnFund(self, arg0: dict) -> None:
        ...
    def onRtnOrder(self, arg0: dict) -> None:
        ...
    def onRtnPosition(self, arg0: dict) -> None:
        ...
    def onRtnPositionProfit(self, arg0: dict) -> None:
        ...
    def onRtnPositionSummary(self, arg0: dict) -> None:
        ...
    def onRtnSpecialOrder(self, arg0: dict) -> None:
        ...
    def onRtnSpotLock(self, arg0: dict) -> None:
        ...
    def onRtnTradeMessage(self, arg0: dict) -> None:
        ...
    def orderLocalInput(self, arg0: dict) -> int:
        ...
    def orderLocalModify(self, arg0: dict) -> int:
        ...
    def orderLocalRemove(self, arg0: dict) -> int:
        ...
    def orderLocalTransfer(self, arg0: dict) -> int:
        ...
    def qryAccount(self, arg0: dict) -> int:
        ...
    def qryAccountCashAdjust(self, arg0: dict) -> int:
        ...
    def qryAccountFeeRent(self, arg0: dict) -> int:
        ...
    def qryAccountMarginRent(self, arg0: dict) -> int:
        ...
    def qryBill(self, arg0: dict) -> int:
        ...
    def qryCombinePosition(self, arg0: dict) -> int:
        ...
    def qryCommodity(self) -> int:
        ...
    def qryContract(self, arg0: dict) -> int:
        ...
    def qryCurrency(self) -> int:
        ...
    def qryExchange(self) -> int:
        ...
    def qryExchangeStateInfo(self, arg0: dict) -> int:
        ...
    def qryFill(self, arg0: dict) -> int:
        ...
    def qryFund(self, arg0: dict) -> int:
        ...
    def qryHisDelivery(self, arg0: dict) -> int:
        ...
    def qryHisFund(self, arg0: dict) -> int:
        ...
    def qryHisMatch(self, arg0: dict) -> int:
        ...
    def qryHisOrder(self, arg0: dict) -> int:
        ...
    def qryHisOrderProcess(self, arg0: dict) -> int:
        ...
    def qryHisPosition(self, arg0: dict) -> int:
        ...
    def qryOrder(self, arg0: dict) -> int:
        ...
    def qryOrderProcess(self, arg0: dict) -> int:
        ...
    def qryPosition(self, arg0: dict) -> int:
        ...
    def qryPositionSummary(self, arg0: dict) -> int:
        ...
    def qrySpecialOrder(self, arg0: dict) -> int:
        ...
    def qrySpotLock(self, arg0: dict) -> int:
        ...
    def qryTradeMessage(self, arg0: dict) -> int:
        ...
    def qryTradingDate(self) -> int:
        ...
    def qryUserTrustDevice(self, arg0: dict) -> int:
        ...
    def requestVertificateCode(self, arg0: str) -> int:
        ...
    def resetPassword(self, arg0: dict) -> int:
        ...
    def selfPasswordInfoOperate(self, arg0: dict) -> int:
        ...
    def setAPINotify(self) -> int:
        ...
    def setHostAddress(self, arg0: str, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: bool) -> int:
        ...
    def setReservedInfo(self, arg0: str) -> int:
        ...
    def setVertificateCode(self, arg0: dict) -> int:
        ...
    def submitUserLoginInfo(self, arg0: dict) -> int:
        ...
    def verificateIdentityInfo(self, arg0: dict) -> int:
        ...
